'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';

export default function WatchClient({ platform, id }: { platform: string, id: string }) {
  const router = useRouter();

  useEffect(() => {
    // We use a client-side redirect so that search engine crawlers 
    // index the OpenGraph metadata generated by the server component, 
    // but human users are seamlessly booted into the main SPA environment
    // with the modal open.
    // We set the platform in localStorage so the SPA loads into the correct theme.
    if (typeof window !== 'undefined') {
      localStorage.setItem('app_platform', platform);
      router.replace(`/?title=${id}`);
    }
  }, [id, platform, router]);

  // Render a seamless loading state while redirecting
  return (
    <div style={{ width: '100vw', height: '100vh', background: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: '40px', height: '40px', border: '3px solid rgba(255,255,255,0.1)', borderTopColor: '#FFF', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
